import { useQuery } from '@tanstack/react-query';
import { getBreakdown } from '../lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { ArrowRight, Activity as ActivityIcon, Users, Settings2, Calculator } from 'lucide-react';

export default function SimplificationBreakdown() {
  const { data: breakdownData, isLoading, error } = useQuery({
    queryKey: ['breakdown'],
    queryFn: getBreakdown
  });

  if (isLoading) return <div className="text-slate-500">Loading breakdown...</div>;
  if (error) return <div className="text-red-500">Error loading breakdown</div>;

  const { rawDebts = [], netBalances = [], simplifiedDebts = [] } = breakdownData?.data || {};

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="space-y-2">
        <h1 className="text-2xl font-bold text-primary flex items-center gap-2">
          <Calculator className="w-6 h-6 text-primary" />
          Debt Simplification Details
        </h1>
        <p className="text-muted">
          See exactly how expenses translate into the final optimized settlements shown on the dashboard.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        
        {/* Step 1: Raw Debts */}
        <div className="space-y-4">
          <div className="flex items-center gap-2 pb-2 border-b border-divider">
            <div className="w-6 h-6 rounded-[4px] bg-background border border-divider flex items-center justify-center text-sm font-bold text-muted">1</div>
            <h2 className="text-lg font-semibold text-primary">Raw Debts</h2>
          </div>
          <p className="text-sm text-muted">Individual debts generated by every expense.</p>
          
          <div className="space-y-3">
            {rawDebts.length === 0 ? (
              <div className="text-sm text-muted italic">No raw debts.</div>
            ) : (
              rawDebts.map((debt, i) => (
                <Card key={i} className="bg-background border border-divider shadow-none">
                  <CardContent className="p-3 flex items-center justify-between text-sm">
                    <div className="flex items-center gap-1.5">
                      <span className="font-semibold" style={{ color: debt.from.color }}>{debt.from.name}</span>
                      <ArrowRight className="w-3 h-3 text-muted" />
                      <span className="font-semibold" style={{ color: debt.to.color }}>{debt.to.name}</span>
                    </div>
                    <span className="font-bold text-primary">₹{debt.amount.toFixed(2)}</span>
                  </CardContent>
                </Card>
              ))
            )}
          </div>
        </div>

        {/* Step 2: Net Standing */}
        <div className="space-y-4">
          <div className="flex items-center gap-2 pb-2 border-b border-divider">
            <div className="w-6 h-6 rounded-[4px] bg-[#1A2338] flex items-center justify-center text-sm font-bold text-primary">2</div>
            <h2 className="text-lg font-semibold text-primary">Net Balances</h2>
          </div>
          <p className="text-sm text-muted">Total Paid minus Total Shared.</p>

          <div className="space-y-3">
            {netBalances.length === 0 ? (
              <div className="text-sm text-muted italic">Everyone is settled up.</div>
            ) : (
              netBalances.map((b, i) => (
                <Card key={i} className="bg-background/50 border-0 shadow-none">
                  <CardContent className="p-3 flex items-center justify-between text-sm">
                    <span className="font-semibold" style={{ color: b.color }}>{b.name}</span>
                    <span className={b.net_balance > 0 ? 'text-emerald-500 font-bold' : 'text-red-500 font-bold'}>
                      {b.net_balance > 0 ? '+' : ''}{b.net_balance.toFixed(2)}
                    </span>
                  </CardContent>
                </Card>
              ))
            )}
          </div>
        </div>

        {/* Step 3: Optimized Result */}
        <div className="space-y-4">
          <div className="flex items-center gap-2 pb-2 border-b border-divider">
            <div className="w-6 h-6 rounded-[4px] bg-emerald-900/20 flex items-center justify-center text-sm font-bold text-emerald-500">3</div>
            <h2 className="text-lg font-semibold text-primary">Simplified</h2>
          </div>
          <p className="text-sm text-muted">The final optimized settlements (Dashboard).</p>

          <div className="space-y-3">
            {simplifiedDebts.length === 0 ? (
              <div className="text-sm text-muted italic">No settlements needed.</div>
            ) : (
              simplifiedDebts.map((debt, i) => (
                <Card key={i} className="bg-emerald-900/20 border border-emerald-500/20 shadow-none">
                  <CardContent className="p-3 flex items-center justify-between text-sm">
                    <div className="flex flex-col gap-1">
                      <span className="font-semibold" style={{ color: debt.from.color }}>{debt.from.name}</span>
                      <ArrowRight className="w-4 h-4 text-emerald-500/50" />
                      <span className="font-semibold" style={{ color: debt.to.color }}>{debt.to.name}</span>
                    </div>
                    <span className="font-bold text-emerald-500 text-lg">₹{debt.amount.toFixed(2)}</span>
                  </CardContent>
                </Card>
              ))
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
